#!/usr/bin/env bash

# dmenu theming
. $HOME/.Xresources

prompt="-p Launch Application:"
colors="-nb \#2C323E -nf \#9899a0 -sb \#81A1C1 -sf \#E5E9F0"

j4-dmenu-desktop --dmenu="dmenu -i $prompt $lines $font $colors"

